-- Run this in your Supabase SQL Editor

-- 1. Create the orders table
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  order_number TEXT NOT NULL,
  table_number TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'received',
  items JSONB NOT NULL,
  total_amount NUMERIC NOT NULL DEFAULT 0
);

-- 2. Enable Realtime for the Kitchen & Customer Dashboard
ALTER PUBLICATION supabase_realtime ADD TABLE public.orders;

-- 3. Disable Row Level Security (RLS) temporarily for MVP testing 
-- (In production, you should enable this and write strict policies)
ALTER TABLE public.orders DISABLE ROW LEVEL SECURITY;
